// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onButtonChange();
void onPumpStateChange();

int activationCounter;
int humiditySensor1;
int humiditySensor2;
bool button;
bool pumpState;

void initProperties(){

  ArduinoCloud.addProperty(activationCounter, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humiditySensor1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humiditySensor2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(button, READWRITE, ON_CHANGE, onButtonChange);
  ArduinoCloud.addProperty(pumpState, READWRITE, ON_CHANGE, onPumpStateChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
